# This should be run from the Skype for Business Online PowerShell module


Set-CsUser -Identity Creig.Allen@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095760
Set-CsUser -Identity David.Anderson@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095762
Set-CsUser -Identity Emad.Attalla@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095763
Set-CsUser -Identity Rick.Barett@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095764
Set-CsUser -Identity Frank.Bartnicke@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095765
Set-CsUser -Identity Brandon.Batchelder@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095766
Set-CsUser -Identity Bill.Bean@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095767
Set-CsUser -Identity Mark.Birecki@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095768
Set-CsUser -Identity Kathleen.Bowles@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095769
Set-CsUser -Identity Terry.Brannon@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095770
Set-CsUser -Identity Ben.Brantley@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095771
Set-CsUser -Identity Aaron.Brothers@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095772
Set-CsUser -Identity Kelly.Burton@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095773
Set-CsUser -Identity Marvin.Burton@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095774
Set-CsUser -Identity Cass.Byrd@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095775
Set-CsUser -Identity David.Caldwell@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095776
Set-CsUser -Identity "De'Juan.Campbell@amgeneral.com" -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095777
Set-CsUser -Identity Jorge.Cornejo@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095778
Set-CsUser -Identity John.Czarski@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095779
Set-CsUser -Identity Richard.Coleman@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095849
Set-CsUser -Identity Heather.Dattolo@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095780
Set-CsUser -Identity Lakshmikanth.Dayanandham@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095839
Set-CsUser -Identity Laura.DeChane@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095781
Set-CsUser -Identity Michael.DeMarco@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095782
Set-CsUser -Identity Angelo.Ditouras@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095783
Set-CsUser -Identity Kathleen.Doherty@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095784
Set-CsUser -Identity Jeff.Dowell@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095785
Set-CsUser -Identity Steve.Drain@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095786
Set-CsUser -Identity Paul.Dutch@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095787
Set-CsUser -Identity Sarah.English@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095909
Set-CsUser -Identity Christopher.Fahnestock@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095789
Set-CsUser -Identity Marcus.Ferguson@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095790
Set-CsUser -Identity Terry.Filice@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095791
Set-CsUser -Identity Eric.Fillip@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095792
Set-CsUser -Identity Brett.Firmingham@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095793
Set-CsUser -Identity Anna.Fisher@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095788
Set-CsUser -Identity Marlene.Fisher@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095794
Set-CsUser -Identity John.Fitzsimons@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095795
Set-CsUser -Identity Robert.Forrest@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095796
Set-CsUser -Identity Barry.Foster@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095797
Set-CsUser -Identity Eric.Foster@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095798
Set-CsUser -Identity Al.Frey@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095799
Set-CsUser -Identity Keith.Gabbard@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12488365575
Set-CsUser -Identity Rhey.Galang@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095801
Set-CsUser -Identity Claudia.Gast@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095802
Set-CsUser -Identity Matthew.George@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095803
Set-CsUser -Identity Michael.Gill@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095804
Set-CsUser -Identity Paul.Gleason@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095805
Set-CsUser -Identity Dawn.Graham@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095806
Set-CsUser -Identity Ray.Grant@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095807
Set-CsUser -Identity Steven.Grate@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095808
Set-CsUser -Identity Dan.Grauer@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095809
Set-CsUser -Identity Tammy.Grauer@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095810
Set-CsUser -Identity Michael.Green@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095811
Set-CsUser -Identity Rhonda.Griffin@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095812
Set-CsUser -Identity James.Griffin@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095813
Set-CsUser -Identity Ronald.Grover@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095814
Set-CsUser -Identity Chris.Hamilton@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095815
Set-CsUser -Identity Kimberly.Hamilton@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095816
Set-CsUser -Identity John.Hanawalt@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095817
Set-CsUser -Identity Scott.Hanchett@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095818
Set-CsUser -Identity Paul.Hanner@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095819
Set-CsUser -Identity Catherine.Harris@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095820
Set-CsUser -Identity Thomas.Harris@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095821
Set-CsUser -Identity Joe.Hayes@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095822
Set-CsUser -Identity Grant.Hayward@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095823
Set-CsUser -Identity Todd.Henker@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095824
Set-CsUser -Identity Joseph.Herman@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095825
Set-CsUser -Identity John.Hoag@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095826
Set-CsUser -Identity LaTonya.Huby@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095827
Set-CsUser -Identity Jeff.Johannsen@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095828
Set-CsUser -Identity Steven.Jonna@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095829
Set-CsUser -Identity Emily.Jump@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095830
Set-CsUser -Identity Burkhard.Kappe@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095831
Set-CsUser -Identity Raminder.Kaur@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095832
Set-CsUser -Identity Douglas.Keller@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095833
Set-CsUser -Identity Ryan.Kimler@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095834
Set-CsUser -Identity Ellen.Koga@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095835
Set-CsUser -Identity Peter.Kopinski@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095836
Set-CsUser -Identity Gus.Kostan@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095837
Set-CsUser -Identity Michael.Kunz@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095838
Set-CsUser -Identity Joseph.LaCola@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095840
Set-CsUser -Identity Carolyn.LaForce@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095841
Set-CsUser -Identity Steven.Laughlin@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095842
Set-CsUser -Identity Nathanial.Letarte@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095843
Set-CsUser -Identity Traci.Lennox@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095844
Set-CsUser -Identity Wendy.Long@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095845
Set-CsUser -Identity Michael.Lubzik@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095846
Set-CsUser -Identity Steve.Luma@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095847
Set-CsUser -Identity Regis.Luther@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095848
Set-CsUser -Identity Scott.Luplow@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095850
Set-CsUser -Identity Kathleen.Macek@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095851
Set-CsUser -Identity Michael.Maiberger@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095852
Set-CsUser -Identity Carla.Maier@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095883
Set-CsUser -Identity Curtis.Malysz@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095853
Set-CsUser -Identity Quin.Malysz@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095854
Set-CsUser -Identity Jerry.Matthews@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095855
Set-CsUser -Identity James.Matusek@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095856
Set-CsUser -Identity John.Mayles@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095857
Set-CsUser -Identity Robert.McCartney@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095858
Set-CsUser -Identity Chris.McFarland@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095859
Set-CsUser -Identity Jennifer.McGrew@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095860
Set-CsUser -Identity Talon.McIntosh@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12488365577
Set-CsUser -Identity Bill.McKinney@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095861
Set-CsUser -Identity Daryl.McNutt@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095862
Set-CsUser -Identity William.Meek@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095863
Set-CsUser -Identity John.Meir@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095864
Set-CsUser -Identity Roger.Mills@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095865
Set-CsUser -Identity Michael.Muglia@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095866
Set-CsUser -Identity Deborah.Murdie@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095867
Set-CsUser -Identity Steven.Napier@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095968
Set-CsUser -Identity Aaron.Nash@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095869
Set-CsUser -Identity Gregg.Nash@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095870
Set-CsUser -Identity Michael.Neiswonger@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095871
Set-CsUser -Identity Norman.Nordstrom@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095872
Set-CsUser -Identity DOliver@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095873
Set-CsUser -Identity Mike.Pachuta@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095874
Set-CsUser -Identity Mark.Paleno@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095875
Set-CsUser -Identity Dave.Parks@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095876
Set-CsUser -Identity Paul.Patyna@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095877
Set-CsUser -Identity Eric.Peterson@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095878
Set-CsUser -Identity Gregory.Pianczk@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095879
Set-CsUser -Identity Paul.Pieragostini@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095880
Set-CsUser -Identity Lisa.Pifher@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095881
Set-CsUser -Identity Carl.Pignato@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095882
Set-CsUser -Identity Tony.Poparad@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095884
Set-CsUser -Identity Beth.Pratt@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095885
Set-CsUser -Identity Robert.Priskey@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095886
Set-CsUser -Identity Darryl.Proctor@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095887
Set-CsUser -Identity Deborah.Proven@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095888
Set-CsUser -Identity Greg.Proven@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095889
Set-CsUser -Identity Charitie.Pruitt@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095891
Set-CsUser -Identity Rob.Quinn@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095892
Set-CsUser -Identity Darrin.Rabideau@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095893
Set-CsUser -Identity Carol.Ralko@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095894
Set-CsUser -Identity Kenneth.Reeves@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095895
Set-CsUser -Identity Thomas.Reinke@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095896
Set-CsUser -Identity Deborah.Reyes@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095897
Set-CsUser -Identity Ruby.Richards@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095898
Set-CsUser -Identity Larry.Rink@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095899
Set-CsUser -Identity Oscar.Robinson@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095890
Set-CsUser -Identity Mark.Rush@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12488365576
Set-CsUser -Identity Carol.Rowe@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095901
Set-CsUser -Identity David.Ruselink@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095902
Set-CsUser -Identity Gregory.Sabat@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095903
Set-CsUser -Identity Eric.Santo@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095904
Set-CsUser -Identity Michael.Schultz@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095905
Set-CsUser -Identity Jennifer.Seidl@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095906
Set-CsUser -Identity Deborah.Shelton@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095907
Set-CsUser -Identity Xinlan.Shi@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095908
Set-CsUser -Identity Mark.Skotak@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095910
Set-CsUser -Identity Darrin.Smith@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095911
Set-CsUser -Identity Mark.Smith@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095912
Set-CsUser -Identity Ron.Specht@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095913
Set-CsUser -Identity Jeffrey.Spehar@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095914
Set-CsUser -Identity Kesavan.Sridharan@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095915
Set-CsUser -Identity Mike.Stetz@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095916
Set-CsUser -Identity Kevin.Sullivan@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095917
Set-CsUser -Identity Mark.Tolly@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095919
Set-CsUser -Identity Ron.Toma@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095920
Set-CsUser -Identity Eva.Tomlinson@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095921
Set-CsUser -Identity Joseph.Valentine@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095922
Set-CsUser -Identity Chris.Vanslager@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095923
Set-CsUser -Identity Kenneth.Verfaillie@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095924
Set-CsUser -Identity Denise.Vidusic@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095925
Set-CsUser -Identity Dennis.Vranich@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095926
Set-CsUser -Identity Ward.Waite@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095927
Set-CsUser -Identity Adil.Wasi@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095928
Set-CsUser -Identity Lyndon.Williams@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095761
Set-CsUser -Identity Lori.Wilson@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095929
Set-CsUser -Identity Robert.Winn@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095930
Set-CsUser -Identity Theodore.Witbrodt@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095931
Set-CsUser -Identity Dave.Wolfe@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095932
Set-CsUser -Identity Brad.Wolkan@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095933
Set-CsUser -Identity Leighton.Wood@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095934
Set-CsUser -Identity Michael.Yan@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095935
Set-CsUser -Identity Robert.Yesta@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095936
Set-CsUser -Identity Alasdair.Young@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095937
Set-CsUser -Identity Matt.Zielinski@amgeneral.com -EnterpriseVoiceEnabled $true -HostedVoicemail $true -OnPremLineUri tel:+12483095938
